### ISSUE TITLE
[FEATURE] scan for previously downloaded content

### ISSUE THREAD

**Issue by r4v3r23** [FallingLights/Teachable-dl#10]
is there a way to get the script to start where it left off in case of an interruption?

**Comment by FallingLights** [comment]
Currently it start from the beginning and checks if the file exists if it does it skips it and goes to the next one. (Videos are also checked for corruption)

If I will have time this weekend I will try implementing a a better way of doing this

**Comment by r4v3r23** [comment]
yes i noticed, but this still takes time. i also had a couple of incomplete videos downloaded that were chopped at the end after my network dropped - should I just replace the course link with those specific videos' links to only download those videos again?

**Comment by reggian** [comment]
I have added subtitle skipping on my fork. I can submit a PR for if desired.

**Comment by FallingLights** [comment]
Hi @reggian!

If you'd like to submit a pull request (PR), that would be really great.

Thanks for your contribution!

**Comment by reggian** [comment]
Adding the PR link here for reference, I see you already pulled it in. #17

**Comment by r4v3r23** [comment]
doesn't seem like this works properly, i just restarted a download and it started from the beginning, redownloading everything instead of skipping
