### ISSUE TITLE
[FEATURE] Download all videos from a lesson with more than one video

### ISSUE THREAD

**Issue by HenestrosaConH** [FallingLights/Teachable-dl#11]
I have came accross some lessons that contain more than one video. Currently, the program just downloads the first one, so I was wondering if it was possible to download all of them.

**Comment by FallingLights** [comment]
Mind sharing the source code of the site, as I have not experienced a site that puts two videos into one page

**Comment by mmicire** [comment]
I'll second this.  I have a training program for exercise that does a workout summary, and then the second video is the actual workout.  Ironically the second video is really the one I need.  Thank you ahead of time.  

https://darkhorseacademy.teachable.com/courses/868447/lectures/15838725

[Workout 15 _ Dark Horse.html.txt](https://github.com/FallingLights/Teachable-dl/files/11360423/Workout.15._.Dark.Horse.html.txt)

**Comment by FallingLights** [comment]
@mmicire @HenestrosaConH Can you test if the latest commit fixes this

**Comment by jehoshua7** [comment]
I had this happen today. There are 22 lectures in a course, and 2 of those lectures have more than one video. Only the first video was downloaded. I'll use Kazam to get the other 2 videos.
