### ISSUE TITLE
[BUG] Cannot Download as Google Chrome Opens upon running the command

### ISSUE THREAD

**Issue by KrishnarajT** [FallingLights/Teachable-dl#12]
**Describe the bug**
Apologies for an issue that I think may be trivial, but every time I run the command given in the README, google chrome is launched, and it asks me to log in. Which upon doing, it just opens the video, and chrome then closes, and I get the message that it couldnt' log in. I also had to try it on google chrome and not anything else, coz of selenium's requirements of having a version over 112. 

**To Reproduce**
1. Site name:
2. command run - the one in readme without any changes, just the url, username and password 
`python main.py --url https://visualpath.teachable.com/courses/ax-technical-d365-september-2022-batch-by-maitra-8-30-pm/lectures/42829022 --email [email] --password [pass]`
...

**Expected behavior**
The video was supposed to downlaod. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux 6.2.8-arch1-1
 - Browser Version 112.0.5615.49 (Official Build) (64-bit)

**Comment by FallingLights** [comment]
Chrome should lunch and the username and password should be autofilled only input that might be required is to solve the cloudflare captcha

**Comment by KrishnarajT** [comment]
It does that, but i get the error message that I couldnt login
```
ERROR: Could not login: Message:
Stacktrace:
#0 0x55e1c5eebfe3 <unknown>
#1 0x55e1c5c2ad36 <unknown>
#2 0x55e1c5c67c4d <unknown>
#3 0x55e1c5c67d61 <unknown>
#4 0x55e1c5ca36a4 <unknown>
#5 0x55e1c5c888ed <unknown>
#6 0x55e1c5ca1232 <unknown>
#7 0x55e1c5c88693 <unknown>
#8 0x55e1c5c5b03a <unknown>
#9 0x55e1c5c5c17e <unknown>
#10 0x55e1c5eaddbd <unknown>
#11 0x55e1c5eb1c6c <unknown>
#12 0x55e1c5ebb4b0 <unknown>
#13 0x55e1c5eb2d63 <unknown>
#14 0x55e1c5e85c35 <unknown>
#15 0x55e1c5ed6138 <unknown>
#16 0x55e1c5ed62c7 <unknown>
#17 0x55e1c5ee4093 <unknown>
#18 0x7f087f942bb5 <unknown>
```
