### ISSUE TITLE
[BUG] ChromeDriver only supports Chrome version 112

### ISSUE THREAD

**Issue by reggian** [FallingLights/Teachable-dl#14]
**Describe the bug**
I might be doing something wrong but when trying to download I receive the following error:

> selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:55045
> from session not created: This version of ChromeDriver only supports Chrome version 112
> Current browser version is 114.0.5702.0

**To Reproduce**
1. Followed the steps in the readme replacing apt with brew

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Version: Chromium 114.0.5702.0

**Comment by FallingLights** [comment]
Try updating https://github.com/ultrafunkamsterdam/undetected-chromedriver to the latest version or downgrade chrome to version 112

**Comment by reggian** [comment]
@FallingLights I have the latest undetected chrome driver, downgrading chrome to version 112 did the trick, yes. Thanks.
