### ISSUE TITLE
Getting Stale Element Reference Error

### ISSUE THREAD

**Issue by surya-ravi** [FallingLights/Teachable-dl#19]
Could you please have a look and let me know what I could be doing wrong? Thanks!

ERROR: Could not download course: https://school.internetlifestylehub.com/courses/enrolled/831151 cause: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=112.0.5615.55)
Stacktrace:
0   undetected_chromedriver             0x000000010ef12ae8 undetected_chromedriver + 4958952
1   undetected_chromedriver             0x000000010ef0a7b3 undetected_chromedriver + 4925363
2   undetected_chromedriver             0x000000010eacc1d6 undetected_chromedriver + 475606
3   undetected_chromedriver             0x000000010ead0274 undetected_chromedriver + 492148
4   undetected_chromedriver             0x000000010eacfe56 undetected_chromedriver + 491094
5   undetected_chromedriver             0x000000010ead02fc undetected_chromedriver + 492284
6   undetected_chromedriver             0x000000010eb0f63c undetected_chromedriver + 751164
7   undetected_chromedriver             0x000000010eb0fc81 undetected_chromedriver + 752769
8   undetected_chromedriver             0x000000010eb020f3 undetected_chromedriver + 696563
9   undetected_chromedriver             0x000000010eb35c3d undetected_chromedriver + 908349
10  undetected_chromedriver             0x000000010eb018f1 undetected_chromedriver + 694513
11  undetected_chromedriver             0x000000010eb35dce undetected_chromedriver + 908750
12  undetected_chromedriver             0x000000010eb5125b undetected_chromedriver + 1020507
13  undetected_chromedriver             0x000000010eb359e3 undetected_chromedriver + 907747
14  undetected_chromedriver             0x000000010eaffaef undetected_chromedriver + 686831
15  undetected_chromedriver             0x000000010eb0100e undetected_chromedriver + 692238
16  undetected_chromedriver             0x000000010eece9ad undetected_chromedriver + 4680109
17  undetected_chromedriver             0x000000010eed3c12 undetected_chromedriver + 4701202
18  undetected_chromedriver             0x000000010eeda79f undetected_chromedriver + 4728735
19  undetected_chromedriver             0x000000010eed4b7a undetected_chromedriver + 4705146
20  undetected_chromedriver             0x000000010eea727e undetected_chromedriver + 4518526
21  undetected_chromedriver             0x000000010eef4908 undetected_chromedriver + 4835592
22  undetected_chromedriver             0x000000010eef4a87 undetected_chromedriver + 4835975
23  undetected_chromedriver             0x000000010ef0400f undetected_chromedriver + 4898831
24  libsystem_pthread.dylib             0x00007ff8139ea1d3 _pthread_start + 125
25  libsystem_pthread.dylib             0x00007ff8139e5bd3 thread_start + 15

**Comment by FallingLights** [comment]
Hello did you still have this issue?

**Comment by surya-ravi** [comment]
Hello, i think you can close this 👍 Thanks.
