### ISSUE TITLE
[FEATURE] Locally save images

### ISSUE THREAD

**Issue by uwidev** [FallingLights/Teachable-dl#20]
**Is your feature request related to a problem? Please describe.**
When viewed in an offline environment, images do not load.

**Describe the solution you'd like**
Save images locally and use those in place of server images.

**Describe alternatives you've considered**
I can connect to the internet (which goes against the focus of this project) or manually save all images when I'm online (which should be scriptable).

**Additional context**
Seems to only save videos to local on my end, images are ignored? Images are still very important to learning curriculum.

**Comment by FallingLights** [comment]
Can you give me a example of which images you would want to be downloaded

**Comment by uwidev** [comment]
So instead of videos, some creators instead use images or GIFS as quick reference material for their users. When teachable-dl runs, it seems to only save a link to the resource, rather than the resource itself. This means that you must be online for the scraped html to view the images, but it would be easier (and more accessible) if images were just saved locally.

![image](https://github.com/FallingLights/Teachable-dl/assets/10101319/e48ba23a-7230-49cc-bdfc-124939162e67)
