### ISSUE TITLE
Not working in Chrome 115

### ISSUE THREAD

**Issue by hirowa** [FallingLights/Teachable-dl#25]
In chrome 115, it gets stuck in Cloudflare Captcha

**Comment by Thoxy67** [comment]
Hi @it4need and @hirowa, could you please review my pull request [workaround to bypass Cloudflare on Chrome > 114](https://github.com/FallingLights/Teachable-dl/pull/27) and let me know if it works for you as well? Your feedback would be greatly appreciated.

**Comment by FallingLights** [comment]
Thank you @Thoxy67 for the PR, hopefully it fixes this issue

**Comment by it4need** [comment]
@Thoxy67 @FallingLights It does not fix the issue for me...

**Comment by Thoxy67** [comment]
Hey @it4need! 👋

Have you tried clicking on the captcha on the second tab that opens after the Cloudflare page is detected? ⚙️ Trying to validate the captcha on the first tab will trigger detection and result in a page reload with the same captcha.

Alternatively, you can manually open a new tab to validate the captcha. Just keep in mind that the first tab will always be detected. 🕵️‍♀️

**Comment by FallingLights** [comment]
@Thoxy67, I can confirm that the PR is still functioning as expected. Admittedly, the interface can be a bit perplexing due to the dual-tab setup, but once you navigate through it, everything operates smoothly.
