### ISSUE TITLE
[FEATURE] replace uc with seleniumbase

### ISSUE THREAD

**Issue by cyb3rw0lf** [FallingLights/Teachable-dl#26]
I was having lots of trouble to have uc working on apple m1 with chrome_driver 116. Then I tried `seleniumbase` and it worked really well.
You should consider replacing uc with seleniumbase in your code.
https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1477#issuecomment-1680867979

**Comment by FallingLights** [comment]
Hi, I currently dont have time to implement this but fell free to do a PR and ill marge it

**Comment by FallingLights** [comment]
Changed to seleniumbase. So I'll be closing this issue
