### ISSUE TITLE
[BUG] Invisible Chromium window 

### ISSUE THREAD

**Issue by TWry** [FallingLights/Teachable-dl#30]
**Describe the bug**
After starting the script it says that I should click the captcha checkbox. I cannot do that, however, as there is no visible window. I can see the Chromium process but it does not seem to have a GUI. 

**Expected behavior**
A Chromium window is displayed in which I can check the captcha checkbox.

**Desktop (please complete the following information):**
 - OS: Debian bookworm 12.2
 - Browser Version 118

**Comment by TWry** [comment]
Any ideas how I can fix or debug this?

**Comment by totalitarian** [comment]
Same problem here with the latest commit

**Comment by TWry** [comment]
After manually installing Chrome by downloading the package from the Google website and changing the first lines of the `__init__` constructor to:
 
```python
        options = uc.ChromeOptions()
        options.headless = False
        self.driver = uc.Chrome(options=options)
```

it worked, but only one time. Subsequent attempts failed because as far as I can tell the login is skipped by the browser as the user is still authenticated.

**Comment by totalitarian** [comment]
> After manually installing Chrome by downloading the package from the Google website and changing the first lines of the `__init__` constructor to:
> 
> ```python
>         options = uc.ChromeOptions()
>         options.headless = False
>         self.driver = uc.Chrome(options=options)
> ```
> 
> it worked, but only one time. Subsequent attempts failed because as far as I can tell the login is skipped by the browser as the user is still authenticated.

can you post the full init? I get uc is not defined

**Comment by TWry** [comment]
Sorry, you need to add the following import: 
```python
import undetected_chromedriver as uc
```

**Comment by FallingLights** [comment]
Latest commit should fix this issue
