### ISSUE TITLE
[BUG] unsupported course template

### ISSUE THREAD

**Issue by TheRealTripleB** [FallingLights/Teachable-dl#43]
**Describe the bug**
After I have manually authenticated myself for the course, I get the message "Downloader does not support this course template. Please open an issue on github".

**To Reproduce**
1. Site name: https://course.musiconerd.com
2. command run:
python3 main.py --url https://course.musiconerd.com/products/ID_NNN --man_login_url https://course.musiconerd.com/products/ID_NNN

**Additional context**
I have replaced the course ID in the URL for this issue with a placeholder.

**Comment by FallingLights** [comment]
Can you send me a screenshot of the page you are trying to downloas

**Comment by TheRealTripleB** [comment]
![Bildschirmfoto 2024-03-12 um 20 53 17](https://github.com/FallingLights/Teachable-dl/assets/67266910/0d036468-b3e1-4b1c-9592-7d210a4f0d1f)

**Comment by anamyk** [comment]
Same bug here

**Comment by FallingLights** [comment]
Could one of you send me account logins, as i currently dont have access to any course where i could test it.
fl-github@proton.me

**Comment by Kronodile** [comment]
same bug, worked once but never again

**Comment by justtrying2024** [comment]
i use this https://app.singr.tv/ ( which runs under teachable )

result: ERROR: Downloader does not support this course template. Please open an issue on github.

**Comment by eddiewong396** [comment]
I tried with stackskills and got the same error.

**Comment by lukassteiner** [comment]
Same problem here

**Comment by FallingLights** [comment]
> Same problem here.
> I sent you an email @FallingLights if you still need login details.

I'll take a look this week

**Comment by FallingLights** [comment]
> **Describe the bug**
> After I have manually authenticated myself for the course, I get the message "Downloader does not support this course template. Please open an issue on github".
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Site name: https://course.musiconerd.com
> 2. command run:
> python3 main.py --url https://course.musiconerd.com/products/ID_NNN --man_login_url https://course.musiconerd.com/products/ID_NNN
> 
> **Additional context**
> I have replaced the course ID in the URL for this issue with a placeholder.
> 

This site does not seem to run on teachables , so it's out of scope for this project
