### ISSUE TITLE
[FEATURE] Keep the browser from stealing focus

### ISSUE THREAD

**Issue by jdunlap** [FallingLights/Teachable-dl#45]
When downloading a course, the browser repeatedly steals focus.

The browser needs to not steal focus while the script is running to allow the user to complete other tasks while a download is running in the background.

**Comment by famasf1** [comment]
Apparently the issue comes down to how Selenium work. It required a viewport to function. 

Maybe using headless mode will somewhat help. But i imagine the owner of this repo probably though about it already.

**Comment by FallingLights** [comment]
> Apparently the issue comes down to how Selenium work. It required a viewport to function. 
> 
> Maybe using headless mode help. But i imagine the owner of this repo probably though about it already and found out it's more work than it's worth. For now the workaround is simply having 2 screen and just put the focus to other program without minimize the window.

Yes, I did not want to do it headless as login requires you to solve captcha
