### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by r4v3r23** [FallingLights/Teachable-dl#7]
getting "bash: syntax error near unexpected token `newline'" when running ```source env/bin/activate python3 main.py --url <course-url> --email <email> --password <password>``` (with all fields filled out)

**Comment by FallingLights** [comment]
That should be two different commands
``source env/bin/activate`` 
After you run this you  should see (env) or something similar at the start of the line in your terminal (you all have to run this once per terminal session)
then run:
``source env/bin/activate python3 main.py --url <course-url> --email <email> --password <password>``

**Comment by r4v3r23** [comment]
thats exactly what i did and still receive same error. i followed the instructions step by step

**Comment by r4v3r23** [comment]
I removed the <> from each field and didnt get the error, but there is not progress bar or anything, is it downloading in background? where do i see the course videos?

**Comment by FallingLights** [comment]
> I removed the <> from each field and didnt get the error, but there is not progress bar or anything, is it downloading in background? where do i see the course videos?

Proper progress bar is currently not available but you can see YouTube and what the script is currently doing in the terminal if you add ``-v``  when calling the script

**Comment by r4v3r23** [comment]
> > I removed the <> from each field and didnt get the error, but there is not progress bar or anything, is it downloading in background? where do i see the course videos?
> 
> Proper progress bar is currently not available but you can see YouTube and what the script is currently doing in the terminal if you add `-v` when calling the script

added -v and still getting the same blank output. looks like its not downloading then.

my teachable course url is in this format: https://course-name.teachable.com/courses/enrolled/randomnumber

**Comment by FallingLights** [comment]
Can't reproduce the issues on my end
